### ISSUE TITLE
Create a decoupled Drupal Twig Extension

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/plugin-drupal-twig-components#1]
Now that patternengine-php-twig provides a way to register proper Twig Extensions (hooray!) we should probably concentrate on creating a Drupal Twig Extension. 

The extension should be decoupled from both Drupal and Pattern Lab and usable with all kinds of decoupled Twig/Drupal projects. Maybe something that could be used as a part of the stand-alone implementation discussed in https://www.drupal.org/node/2702061

Not sure what would be the best home for this extension, ideally it would be an official Drupal project.

**Comment by EvanLovely** [comment]
This would be amazing. That issue linked has been getting a ton of attention lately!

**Comment by heddn** [comment]
This seems stalled out. Is there any progress, apart from the linked issue?

**Comment by aleksip** [comment]
Not that I know of, I'm afraid.

Using 'presenter' templates in component based Drupal themes seems to be the currently popular solution. With no Drupal specific Twig in the components themselves, there is no need for a Drupal Twig Extension in Pattern Lab. It would still be nice to have a Drupal Twig Extension for other use cases, though.
