### ISSUE TITLE
Include other patterns from .json file

### ISSUE THREAD

**Issue by guiajlopes** [pattern-lab/plugin-drupal-twig-components#11]
Hi, is that possible to include other patterns from a json file?

I have this list

```
<div class="node-list">
    {% for node in items %}
        <div class="node-list__item">
            {{ node }}
        </div>
    {% endfor %}
</div>
```

with this json file

```
{
  "items": [
    {
      "article": {
        "nid": 10,
        "nodeUrl": "/node/10",
        "title": "Example article teaser",
        "showTime": false
      }
    }
  ]
}
```

and I want to render the article as another pattern, but I don't want to include this from twig because I'm using render arrays for that on drupal

**Comment by aleksip** [comment]
Hi, yes you can do that with https://github.com/aleksip/plugin-data-transform.

**Comment by guiajlopes** [comment]
@aleksip Amazing! Thank you :)
